server {
    listen 3000;
    resolver 127.0.0.11;

    location ~ ^/([^/]+)/localhost:(\d+)/(.*)$ {
        set $container_id $1;
        set $port $2;
        set $path $3;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_pass http://$container_id:$port/$path;
    }

    location / {
        add_header Content-Type text/plain;
        return 200 "Nginx Running\n";
    }
}
